version: '3.7'
services:

  mongodb:
    image: mongo:4.2-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    volumes:
      - mongodb:/data/db
      - ./seed/mongo-user.js:/docker-entrypoint-initdb.d/mongo-user.js

  redis:
    image: redis:5.0-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis:/data

  messaging:
    build: ./apps/messaging
    ports:
      - 8080:8080
    depends_on:
      - redis
      - mongodb
    volumes:
      - ./apps/messaging:/app

volumes:
  mongodb:
  redis: